### ISSUE TITLE
Changing wallpaper isn't working on MacOS

### ISSUE THREAD

**Issue by sparksub** [FacerAin/2020-Khuthon-WYGA#2]
npm run dev로 실행 했을 때 MacOS에서 동작이 되질 않습니다.

**Comment by sparksub** [comment]
npm run bulid로도 mac에서 안바뀌네요. 다른 에러 메세지는 안뜹니다.

**Comment by sparksub** [comment]
ChildProcess console.log 내용입니다.


ChildProcess {_events: {…}, _eventsCount: 2, _maxListeners: undefined, _closesNeeded: 3, _closesGot: 0, …}
connected: false
exitCode: -13
killed: false
pid: undefined
signalCode: null
spawnargs: Array(2)
0: "/Users/subinpark/Documents/GitHub_Rep/2020-Khuthon-WYGA/paduck/renderer/public/mac/wallpaper"
1: "/Users/subinpark/Documents/GitHub_Rep/2020-Khuthon-WYGA/paduck/renderer/public/images/wallpaper.jpg"
length: 2
__proto__: Array(0)
spawnfile: "/Users/subinpark/Documents/GitHub_Rep/2020-Khuthon-WYGA/paduck/renderer/public/mac/wallpaper"
stderr: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
stdin: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
stdio: (3) [Socket, Socket, Socket]
stdout: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
Symbol(kCapture): false
_closesGot: 3
_closesNeeded: 3
_events: {close: ƒ, error: ƒ}
_eventsCount: 2
_handle: null
_maxListeners: undefined
__proto__: EventEmitter

**Comment by yongdol503** [comment]
execFile은 실행가능한 응용 프로그램을 새로 프로세스 열어서 실행시키는 메소드 입니다.

mac에 wallpaper는 터미널상에서 명령어로 실행시키는 형태이기에 execFile로는 정상 작동이 되지 않았던겁니다.

그래서 명령어를 실행시키는 exec메소드로 변경하면 문제없이 정상 작동됩니다.
